---
- name: Set timezone
  timezone:
    name: Europe/Moscow

### Network settings
- name: Remove default route
  lineinfile:
    line: "DEFROUTE=no"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0

- name: Add gateway
  lineinfile:
    line: "GATEWAY=192.168.10.10"
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1  
  notify:
    - restart network      

